### ISSUE TITLE
Decrease lower bound on `Cabal`?

### ISSUE THREAD

**Issue by Gabriella439** [ndmitchell/js-jquery#2]
Would it be possible to decrease the required `Cabal` version to 1.8 instead of 1.18?  I'm not sure if this library requires any specific feature that's not available in 1.8

The reason I'm asking is that 1.8 is the `Cabal` version that usually ships with `ghc 7.6.3`.  I understand that users can upgrade `Cabal` so it's not a high priority thing to fix

**Comment by ndmitchell** [comment]
This bound is in common with all my packages. I want to ship the changelog and readme with my packages, and the morally correct section for that is extra-docs. Cabal < 1.18 ignore those sections without comment, and it wasn't a problem, so I typically just put a bound on 1.8. Unfortunately the latest version of cabal (HEAD) gives an error if you use extra-docs but don't require 1.18, so I added the bound. There are other options (don't ship the files, put them in extra-source-files), but I didn't realise 7.6 was so far behind, and I've generally had to go for newer Cabal's to get anything resolving anyway. Thoughts?

**Comment by Gabriella439** [comment]
Yeah, in that case I think it makes sense to keep the `Cabal >= 1.18 bound` since you definitely need it.  I was just asking because I wasn't very familiar with what features correlated with which Cabal versions

Either way I have a work-around on my end, so I think it's fine not to fix this

**Comment by ivan-m** [comment]
It's not going to help now (without the rather fugly editing of .cabal files on Hackage), but maybe in future use corresponding lower bounds on base (`>= 4.7 && < 5` rather than the current `== 4.*`) to reflect this?

I've just been bitten by this issue with my Travis-CI builds against older versions of GHC, as criterion depends upon this library (unversioned).

**Comment by ndmitchell** [comment]
@ivan-m My Travis-CI builds are capable of building this all the way back to GHC 7.4, and I think they used to go back as far as 7.0 - a base library bound would be inaccurate. I suggest on Travis you install a newer Cabal first - which is what I do: https://github.com/ndmitchell/neil/blob/master/travis.sh#L21.

**Comment by ivan-m** [comment]
@ndmitchell ta!

**Comment by ndmitchell** [comment]
For info, I had to go way past Cabal-1.16 a long time ago since it couldn't generate install plans for certain packages.
